### ISSUE TITLE
Деплой проекта на сервер

### ISSUE THREAD

**Issue by mikhailborodin** [thinknetica-django-lab-03/viktorshm-github#107]
**Что?**

Вот мы и подошли к завершению нашего учебного проекта. Финальный штрихом логично было бы развернуть проект на сервере, чтобы он был доступен не только на локальном компьютере, но и в сети, чтобы его можно было показать в портфолио

**Задачи**

1. Изучить сервис heroku и установить Heroku CLI
2. Создать heroku приложение и зарелизить его на сервер

**Ресурсы**

* https://www.codingforentrepreneurs.com/blog/django-docker-production-heroku

**Comment by viktorshm-github** [comment]
Создать приложение получилось, но не даёт установить редис бесплатно. И приложение не запускается. Я могу задеплоить у себя на сервере?

**Comment by viktorshm-github** [comment]
Получилось: http://77.223.98.170:8000/
